### ISSUE TITLE
Are there hardware requirements to execute the script?

### ISSUE THREAD

**Issue by chsnt** [ai-forever/ru-gpts#94]
Are there hardware requirements to execute the script?

I get the following error when executing **ru-gpts/pretrain_transformers.py** from [example](https://github.com/ai-forever/ru-gpts/blob/master/examples/Finetune_RuGPTs_with_HF.ipynb)

```
Epoch:   0%|          | 0/5 [00:00<?, ?it/s]
Iteration:   0%|          | 0/3 [00:00<?, ?it/s]
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

![image](https://user-images.githubusercontent.com/43132492/181440523-2ee0b79e-cb3b-4e12-be34-55905dfd0dfb.png)

**Comment by Den4ikAI** [comment]
depending on which model you train

**Comment by chsnt** [comment]
Small rugpt, like in example

**Comment by Den4ikAI** [comment]
4 gigabytes is enough for inference, and 9 gb for training (it all depends on the batch size). What equipment do you have?

**Comment by Den4ikAI** [comment]
I tested this code in google colab. It works fine

**Comment by chsnt** [comment]
У меня не работает ни в colab, ни в Jupiter , ни на виртуальной машине с linux через ide
Может быть есть требования к формату train.txt ?
У меня строка через пустую строку

```
Строка1

Строка2

Строка3

...
```

**Comment by chsnt** [comment]
На локальной машине 4гб видеопамяти и 64гб оперативной

**Comment by Den4ikAI** [comment]
Если вы откроете оригинальный обучающий набор, то вы увидите формат) 

<s>sample</s>
<s>sample</s>

**Comment by Den4ikAI** [comment]
4 гига мало, откройте код примера в google colab, и удалите строки где начинается загрузка с дропбокс. Потом просто загрузите эти данные через файловый менеджер google colab

**Comment by chsnt** [comment]
Я так и сделал  . Только свой дропбокс создал и заменил ссылку. Все также зависло на тренировке модели. Я думаю проблема в формате, попробую его изменить

**Comment by chsnt** [comment]
Нужны ли эти html теги вроде <s></s>

**Comment by Den4ikAI** [comment]
Обязательно

**Comment by chsnt** [comment]
Наличие тега подразумевет наличие входного и выхожного параметра. Я же не хочу давать входных данных, мне нужен бредогенератор уровня Нейрорамзана.
То есть я хотел скормить ему тексты твиттов в одном стиле и чтобы он мне генерил новые твитты.

Может нужно запустить тренеровку с другими параметрами для моих целей?

**Comment by chsnt** [comment]
4 часа исполняется в colab, это норма?
Запускал без eval

**Comment by Den4ikAI** [comment]
какую видеокарту вам выдали?

**Comment by chsnt** [comment]
Все, разобрался. 
Денчик, заходи в /pr , в нейротред

**Comment by David3456789** [comment]
> какую видеокарту вам выдали?
Добрый день. 
Подскажите, пожалуйста, какой объём видеопамяти необходим для дообучения моделей Large и XL?

**Comment by king-menin** [comment]
For finetune ruGPT3XL with batch size 1 we need around 32GB GPU Memory
