### ISSUE TITLE
Ускорение инференса  rugpt3-large

### ISSUE THREAD

**Issue by Den4ikAI** [ai-forever/ru-gpts#95]
Приветствую! Имеется отфайнтюненая rugp3-large и пк с 3 tesla m40. Возможно ли ускорить работу модели используя все 3 карты?

**Comment by king-menin** [comment]
Мы пока не занимались ускорением инференса. Вы можете на каждой запустить по модели и тогда для пользователей будет ускорение, если их много. также можете попробовать использовать [onnxruntime ](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers)или [deepspeed inference](https://www.deepspeed.ai/tutorials/inference-tutorial/).
