### ISSUE TITLE
Unable to use RuGPT3FinetuneHF.ipynb Colab notebook

### ISSUE THREAD

**Issue by MsSurgeon** [ai-forever/ru-gpts#97]
During the process of execution of the Colab notebook "RuGPT3FinetuneHF.ipynb" with fine-tuning error appears: 
<img width="1743" alt="RuGPT3FinetuneHF ipynb - Colaboratory 2022-11-30 10-41-27" src="https://user-images.githubusercontent.com/20087728/204736132-eb113603-a3a4-4ab5-8403-a023f44663b9.png">

**Comment by king-menin** [comment]
Please, run our code on machine with gpu and cuda drivers
