### ISSUE TITLE
No "nvcc" utilite founded during environment installation 

### ISSUE THREAD

**Issue by MsSurgeon** [ai-forever/ru-gpts#99]
<img width="402" alt="ruGPT3XL_generation ipynb - Colaboratory 2022-11-30 11-02-21" src="https://user-images.githubusercontent.com/20087728/204740622-5dc52f7b-aa8e-4352-b0ed-835018d54cf9.png">

**Comment by king-menin** [comment]
Please, run our code on machine with gpu and cuda drivers

**Comment by Kulinark** [comment]
![Снимок экрана 2022-12-19 142454](https://user-images.githubusercontent.com/35849659/208415733-72126807-c3d6-45d4-8975-d727beeffc22.png)
If you run the example from the notebook, then here is the fastest way to fix this problem

**Comment by king-menin** [comment]
try run the following [example](https://github.com/ai-forever/ru-gpts/blob/master/examples/RuGPT3FinetuneHF.ipynb)
